[project]
name = "race-car"
version = "0.1.0"
description = "Race car solution"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "loguru>=0.7.3",
    "numpy>=2.3.2",
    "pydantic>=2.11.7",
    "pygame>=2.6.1",
    "torch>=2.7.1",
    "uvicorn>=0.35.0",
]
